[package]
name = "laurel"
version = "0.3.1"
authors = ["Hilko Bengen <bengen@hilluzination.de>",
           "Sergej Schmidt <sergej@msgpeek.net>"]
edition = "2018"
rust-version = "1.48"
description = "Transform Linux Audit logs for SIEM usage"
homepage = "https://github.com/threathunters-io/laurel"
repository = "https://github.com/threathunters-io/laurel"
license = "GPL-3.0-or-later"
keywords = ["linux", "audit", "parser", "log", "json"]
categories = ["encoding"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
nom = ">= 0"
lazy_static = ">= 1.4"
getopts = ">= 0.2"
serde = { version = ">= 1", features = ["derive"] }
serde_json = { version = ">= 1", features = ["preserve_order"] }
indexmap = ">= 1"
toml = ">= 0.5"
nix = ">= 0.22"
caps = ">= 0.5"
libc = ">= 0.2"
posix-acl = ">= 1"

[build-dependencies]
bindgen = ">= 0.56"
# cc = ">= 1"

[dev-dependencies]
bencher = ">= 0"
gperftools = ">= 0"

[[bench]]
name = "coalesce_execve"
harness = false
