[package]
name = "laurel"
version = "0.1.2"
authors = ["Hilko Bengen <bengen@hilluzination.de>",
           "Sergej Schmidt <sergej@msgpeek.net>"]
edition = "2018"
description = "Transform Linux Audit logs for SIEM usage"
homepage = "https://github.com/threathunters-io/laurel"
license = "GPL-3.0-or-later"
keywords = ["linux", "audit", "log", "json", "security"]
categories = ["encoding"]

[features]
static = [] # static build, causes libacl and libc to be linked statically into the binary.

[badges]
maintencance = { status = "actively-developed" }

[dependencies]
peg = ">= 0.7"
lazy_static = ">= 1.4"
getopts = ">= 0.2"
serde = { version = ">= 1", features = ["derive"] }
serde_json = { version = ">= 1", features = ["preserve_order"] }
indexmap = ">= 1"
toml = ">= 0.5"
nix = ">= 0.22"
caps = ">= 0.5"
libc = ">= 0.2"
posix-acl = ">= 1"
